package strips;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * 
 * An Operator defines an operator for the problem being solved
 * by the linear planner. It is identified by its name and it can
 * have 0 or more parameters. They may, or may not, be instantiated.
 * Every operator has three lists of predicates: the preconditions,
 * the adds and the deletes.
 * 
 * Operators can be pushed into the stack of goals used by the
 * planning algorithm.
 * 
 * @author Javier Beltran, Jorge Rodriguez
 *
 */
public class Operator implements Stackable {
	
	private String name;
	private List<Parameter> params;
	
	private List<Predicate> preconditions;
	private List<Predicate> adds;
	private List<Predicate> deletes;

	/**
	 * Creates an Operator given its name, parameters, preconditions,
	 * adds and deletes.
	 */
	public Operator(String name, List<Predicate> preconditions, 
			List<Predicate> adds, List<Predicate> deletes, Parameter... params) {
		this.name = name;
		this.params = Arrays.asList(params);
		
		this.preconditions = preconditions;
		this.adds = adds;
		this.deletes = deletes;
	}
	
	/**
	 * Creates an operation from an existing operation. That is, creates a copy
	 * of an existing operation with another reference.
	 */
	public Operator(Operator op) {
		/* Copies the name and parameters of the operator */
		this.name = op.getName();
		this.params = new ArrayList<Parameter>();
		for (Parameter p : op.getParams()) {
			this.params.add(new Parameter(new String(p.getName()), new String(p.getValue())));
		}
		
		/* Copies the preconditions list of the operator */
		List<Predicate> preconditions = new ArrayList<>();
		for (Predicate pred : op.getPreconditions()) {
			List<Parameter> ps = new ArrayList<Parameter>();
			for (Parameter p : pred.getParams()) {
				ps.add(new Parameter(new String(p.getName()), new String(p.getValue())));
			}
			Predicate newPred = new Predicate(pred.getName(), ps);

			preconditions.add(newPred);
		}
		this.preconditions = preconditions;
		
		/* Copies the adds list of the operator */
		List<Predicate> adds = new ArrayList<>();
		for (Predicate pred : op.getAdds()) {
			List<Parameter> ps = new ArrayList<Parameter>();
			for (Parameter p : pred.getParams()) {
				ps.add(new Parameter(new String(p.getName()), new String(p.getValue())));
			}
			Predicate newPred = new Predicate(pred.getName(), ps);

			adds.add(newPred);
		}
		this.adds = adds;
		
		/* Copies the deletes list of the operator */
		List<Predicate> dels = new ArrayList<>();
		for (Predicate pred : op.getPreconditions()) {
			List<Parameter> ps = new ArrayList<Parameter>();
			for (Parameter p : pred.getParams()) {
				ps.add(new Parameter(new String(p.getName()), new String(p.getValue())));
			}
			Predicate newPred = new Predicate(pred.getName(), ps);

			dels.add(newPred);
		}
		this.deletes = dels;
	}
	
	/**
	 * Instantiates the parameters of an operator using the predicate that
	 * is generated by the operation in the plan. Parameters should be properly
	 * tagged with distinctive names, so they can be translated to the operation.
	 */
	public Operator instantiate(Predicate pred) {
		Operator copiedOp = new Operator(this);
		/* Updates parameters of operator with the ones of predicate */
		copiedOp.setParams(updateList(pred.getParams(), copiedOp.getParams()));
		
		/* Updates parameters for the predicates in preconditions, adds and deletes */
		for (Predicate prec : copiedOp.getPreconditions()) {
			prec.setParams(updateList(pred.getParams(), prec.getParams()));
		}
		for (Predicate add : copiedOp.getAdds()) {
			add.setParams(updateList(pred.getParams(), add.getParams()));
		}
		for (Predicate del : copiedOp.getDeletes()) {
			del.setParams(updateList(pred.getParams(), del.getParams()));
		}
				
		return copiedOp;
	}
	
	/**
	 * Updates a list of parameters with the parameters of a predicate.
	 */
	private List<Parameter> updateList(List<Parameter> copy, List<Parameter> paste) {
		for (int i=0; i<paste.size(); i++) {
			for (int j=0; j<copy.size(); j++) {
				if (paste.get(i).getName().equals(copy.get(j).getName())) {
					paste.get(i).setValue(copy.get(j).getValue());
				}
			}
		}
		return paste;
	}
	
	
	/* Getters and setters */

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public List<Parameter> getParams() {
		return params;
	}

	public void setParams(List<Parameter> params) {
		this.params = params;
	}

	public List<Predicate> getPreconditions() {
		return preconditions;
	}

	public void setPreconditions(List<Predicate> preconditions) {
		this.preconditions = preconditions;
	}

	public List<Predicate> getAdds() {
		return adds;
	}

	public void setAdds(List<Predicate> adds) {
		this.adds = adds;
	}

	public List<Predicate> getDeletes() {
		return deletes;
	}

	public void setDeletes(List<Predicate> deletes) {
		this.deletes = deletes;
	}
	
	public String toString() {
		String s = name + "(";
		for (int i=0; i<params.size(); i++) {
			s += params.get(i).toString();
			s += (i < params.size()-1) ? ", " : ")";
		}
		return s;
	}
	
}
